name: gabutdm
version: "1.6.5"
grade: stable
base: core20
summary: Simple and Faster Download Manager
description: |
    Gabut Download Manager application that can download all you need like Link URIs Metallink Magnetlink Torrents using Aria2c and,
    an application that has a local server service interface.
    can also accept file transfers from smartphones.

confinement: strict
package-repositories:
  - type: apt
    components: [main]
    suites: [focal]
    key-id: 2B067CC53533F081B664BF72F6CBED8742796C8E
    url: http://ppa.launchpad.net/torik-habib/gabutdm/ubuntu
parts:
  gabutdm:
    after: [desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/gabutakut/gabutdm.git
    override-build: |
        snapcraftctl build
        sed -i -E 's|^(Icon[^=]*)=.*|\1=/usr/share/icons/hicolor/128x128/apps/com.github.gabutakut.gabutdm.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.gabutakut.gabutdm.desktop
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
        - libsoup2.4-dev
        - libcanberra-dev
        - libcairo2-dev
        - libsqlite3-dev
        - libqrencode-dev
        - libxtst-dev
        - libx11-dev
        - libgee-0.8-dev
        - libjson-glib-dev
        - libgdk-pixbuf2.0-dev
        - libhandy-1-dev
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
        - libcanberra0
        - libqrencode4
        - aria2
        - libhandy-1-0
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  gabutdm:
    command: usr/bin/com.github.gabutakut.gabutdm
    desktop: usr/share/applications/com.github.gabutakut.gabutdm.desktop
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - network
      - home
    build-environment:
        - PATH: /snap/gnome-3-38-2004-sdk/current/usr/bin:$PATH
        - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/snap/gnome-3-38-2004-sdk/current/usr/share:/usr/share:$XDG_DATA_DIRS
        - LD_LIBRARY_PATH: /snap/gnome-3-38-2004-sdk/current/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-3-38-2004-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/gnome-3-38-2004-sdk/current/usr/lib:/snap/gnome-3-38-2004-sdk/current/usr/lib/vala-current:/snap/gnome-3-38-2004-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        - PKG_CONFIG_PATH: /snap/gnome-3-38-2004-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-3-38-2004-sdk/current/usr/lib/pkgconfig:/snap/gnome-3-38-2004-sdk/current/usr/share/pkgconfig:$PKG_CONFIG_PATH
        - GETTEXTDATADIRS: /snap/gnome-3-38-2004-sdk/current/usr/share/gettext-current:$GETTEXTDATADIRS
        - GDK_PIXBUF_MODULE_FILE: /snap/gnome-3-38-2004-sdk/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-current/loaders.cache
        - ACLOCAL_PATH: /snap/gnome-3-38-2004-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
        - PYTHONPATH: /snap/gnome-3-38-2004-sdk/current/usr/lib/python3.8:/snap/gnome-3-38-2004-sdk/current/usr/lib/python3/dist-packages${PYTHONPATH:+:$PYTHONPATH}
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
      GTK_USE_PORTAL: '1'
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
    layout:
      /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
        bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
      /usr/share/xml/iso-codes:
        bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
    slots: [ dbus-gabutdm ]
slots:
  dbus-gabutdm:
    interface: dbus
    bus: session
    name: com.github.gabutakut.gabutdm
plugs:
  gnome-3-38-2004:
    default-provider: gnome-3-38-2004
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
